# This is a basic workflow to help you get started with Actions

name: Purbeurre-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      main
  pull_request:
    branches:
      [main, Setup-CI-CD]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  - env:
      DATABASE_PASSWORD: 'my_db_password'
      SECRET_KEY: 'my_secret_key'

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Running tests
        run: pipenv run pytest
