# This is a basic workflow to help you get started with Actions

name: Purbeurre-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      main
  pull_request:
    branches:
      [main, Setup-CI-CD]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    env:
      DATABASE_PASSWORD: 'my_db_password'
      SECRET_KEY: 'my_secret_key'
      MOZ_HEADLESS: 1

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: 'purbeurre_db'
          POSTGRES_USER: 'purbeurre_db_admin'
          POSTGRES_PASSWORD: 'my_db_password'
        ports:
          - 5432:5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
          mkdir geckodriver
          tar -xzf geckodriver-v0.28.0-linux64.tar.gz -C geckodriver
          export PATH=$PATH:$PWD/geckodriver

      - name: Running tests
        run: pipenv run pytest --driver Firefox
